### ISSUE TITLE
 Impossible to setup WebAPI

### ISSUE THREAD

**Issue by Hiobi** [BanManagement/BanManager-WebAPI#155]
Hi! 

## How to reproduce
I tried to setup BanManager-WebAPI following [this guide](https://banmanagement.com/setup)

I configured everything (MySQL, domain etc) but right after I created Admin user, I got error and configuration don't finalize.

I tried to install it under Debian 9 (server) and Debian 10 (desktop), same error happened.

## Environment details

**OS**: Debian 9 and Debian 10
**Node**: v10.16.3 and 12.9.1
**NPM**: v6.9.0 and 6.10.2

## Logs

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@6.10.2
3 info using node@v12.9.1
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle bm-api@1.0.0~presetup: bm-api@1.0.0
6 info lifecycle bm-api@1.0.0~setup: bm-api@1.0.0
7 verbose lifecycle bm-api@1.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle bm-api@1.0.0~setup: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Spigot/BanManager-WebAPI/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle bm-api@1.0.0~setup: CWD: /home/user/Spigot/BanManager-WebAPI
10 silly lifecycle bm-api@1.0.0~setup: Args: [ '-c', 'node bin/bm-cli setup' ]
11 silly lifecycle bm-api@1.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle bm-api@1.0.0~setup: Failed to exec setup script
13 verbose stack Error: bm-api@1.0.0 setup: `node bin/bm-cli setup`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid bm-api@1.0.0
15 verbose cwd /home/user/Spigot/BanManager-WebAPI
16 verbose Linux 4.19.0-5-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
18 verbose node v12.9.1
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error bm-api@1.0.0 setup: `node bin/bm-cli setup`
22 error Exit status 1
23 error Failed at the bm-api@1.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by confuser** [comment]
API has been merged with the WebUI
