### ISSUE TITLE
Issue with WebAPI on install

### ISSUE THREAD

**Issue by KnowWolf** [BanManagement/BanManager-WebAPI#188]
Trying to install WebAPI on ubuntu 18.04 using 

- node v8.12.0
- npm v6.13.4 

Error Log

```0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.12.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle bm-api@1.0.0~presetup: bm-api@1.0.0
6 info lifecycle bm-api@1.0.0~setup: bm-api@1.0.0
7 verbose lifecycle bm-api@1.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle bm-api@1.0.0~setup: PATH: /root/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/banmanager/BanManager-WebAPI/node_modules/.bin:/root/.nv$
9 verbose lifecycle bm-api@1.0.0~setup: CWD: /home/banmanager/BanManager-WebAPI
10 silly lifecycle bm-api@1.0.0~setup: Args: [ '-c', 'node bin/bm-cli setup' ]
11 silly lifecycle bm-api@1.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle bm-api@1.0.0~setup: Failed to exec setup script
13 verbose stack Error: bm-api@1.0.0 setup: `node bin/bm-cli setup`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid bm-api@1.0.0
15 verbose cwd /home/banmanager/BanManager-WebAPI
16 verbose Linux 4.15.0-74-generic
17 verbose argv "/root/.nvm/versions/node/v8.12.0/bin/node" "/root/.nvm/versions/node/v8.12.0/bin/npm" "run" "setup"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error bm-api@1.0.0 setup: `node bin/bm-cli setup`
22 error Exit status 1
23 error Failed at the bm-api@1.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by confuser** [comment]
API has been merged with the WebUI
